import Head from "next/head";
import { Inter } from "@next/font/google";
import { LeftSide, RightSide } from "../components/ui/Ui";
import Slide from "../components/partials/Slide";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Colegiado do Curso da Engenharia Elétrica </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="p-2">
        <div className="gap-1  w-11/12 m-auto grid grid-cols-11">
          <RightSide />
          <div className="bg-orange-400 col-span-9">
            <Slide />
          </div>
          <LeftSide />
        </div>
      </main>
    </>
  );
}
